### DISCUSSION TITLE
VReplication:  When will the VReplication entry in mysql.vreplication table be deleted?

### DISCUSSION THREAD

**Discussion by newborn22** [wesql/wescale#354] [Q&A] [answered]
VReplication:  When will the VReplication entry in mysql.vreplication table be deleted?

When one vreplication workflow of onlineDDL finished, it will still keep its entry in mysql.vreplication table, just like this:

```
*************************** 2. row ***************************
                   id: 2
             workflow: 16a61c86_7d60_11ee_9efc_da3720e3a51d
               source: keyspace:"testdb" shard:"0" filter:{rules:{match:"_ff44cd38_7d5c_11ee_9efc_da3720e3a51d_20231107190127_vrepl" filter:"select `id` as `id`, `name` as `name`, `age` as `age`, `email` as `email` from `test_table`" source_unique_key_columns:"id" target_unique_key_columns:"id" source_unique_key_target_columns:"id"}}
                  pos: MySQL56/706c0824-7d5c-11ee-8906-645ea9381de9:1-3633
             stop_pos: NULL
              max_tps: 9223372036854775807
  max_replication_lag: 9223372036854775807
                 cell: 
         tablet_types: in_order:REPLICA,PRIMARY
         time_updated: 1699356222
transaction_timestamp: 1699356221
                state: Stopped
   state_before_pause: NULL
              message: stopped for online DDL cutover
              db_name: testdb
          rows_copied: 0
                 tags: 
       time_heartbeat: 0
        workflow_type: 5
       time_throttled: 0
  component_throttled: 
    workflow_sub_type: 0
 defer_secondary_keys: 0

```
